//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class News
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "عنوان خبر")]
        [Required(ErrorMessage = "لطفا مقدار {0} را وارد کنید")]
        public string Title { get; set; }

        [Display(Name = "عنوان کوتاه خبر")]
        [Required(ErrorMessage = "لطفا مقدار {0} را وارد کنید")]
        [DataType(DataType.MultilineText)]
        public string ShortText { get; set; }

        [Display(Name = "متن کامل صفحه")]
        [Required(ErrorMessage = "لطفا مقدار {0} را وارد کنید")]
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }

        [Display(Name = "تاریخ خبر")]
        [Required(ErrorMessage = "لطفا مقدار {0} را وارد کنید")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime CreatedOn { get; set; }

        [Display(Name = "منتشر شده")]
        public bool IsPublish { get; set; }

        [Display(Name = "گروه خبر")]
        [Required(ErrorMessage = "لطفا مقدار {0} را وارد کنید")]
        public int GroupId { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
